name: Run Daily Script

on:
  schedule:
    - cron: '48 3 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run the script
        run: node cron/index.js
