name: Run Daily Script

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Run the script
      run: node cron/index.js
