name: Run Daily Script

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Run the script
      env:
        ACTIONS_STEP_DEBUG: true
        ACTIONS_RUNNER_DEBUG: true
      run: node cron/index.js
