name: Run Daily Script

on:
  schedule:
    - cron: "50 11 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js 23
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run the script
        run: node --env-file .env --experimental-strip-types cron/index.ts
